version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    groups:
      serde:
        patterns:
          - serde
          - "serde_*"
          - "serde-*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
