[workspace]
members = ["gengo", "gengo-bin"]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/spenserblack/gengo"
readme = "README.md"
license = "MIT OR Apache-2.0"

keywords = []
