[package]
name = "gengo"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/spenserblack/gengo"
readme = "../README.md"

[dependencies]
gengo-impl = { version = "0.1", path = "../gengo-impl" }
regex = "1"
